// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyatnuhwilxwwhlyhrbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5YXRudWh3aWx4d3dobHlocmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDk0MzksImV4cCI6MjA2NTcyNTQzOX0._2v7sWFaDXLtuPz3pPkADvaDHbdcCeh6AJLagTxX17E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);