// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey);

export const insertFarmer = async (farmerData: Database['public']['Tables']['farmers']['Insert']) => {
  return await supabase
    .from('farmers')
    .insert([farmerData])
    .select()
}

export const insertBuyer = async (buyerData: Database['public']['Tables']['buyers']['Insert']) => {
  return await supabase
    .from('buyers')
    .insert([buyerData])
    .select()
}

export const getFarmers = async () => {
  return await supabase
    .from('farmers')
    .select('*')
    .order('created_at', { ascending: false })
}

export const getBuyers = async () => {
  return await supabase
    .from('buyers')
    .select('*')
    .order('created_at', { ascending: false })
}

export const getFarmersByLocation = async (location: string) => {
  return await supabase
    .from('farmers')
    .select('*')
    .ilike('location', `%${location}%`)
    .order('created_at', { ascending: false })
}

export const getBuyersByLocation = async (location: string) => {
  return await supabase
    .from('buyers')
    .select('*')
    .ilike('location', `%${location}%`)
    .order('created_at', { ascending: false })
}